#!/usr/bin/env bash

set -e

real_path=$(realpath $0)
echo "Real path is '$real_path'"

dir_name=$(dirname $real_path)
echo "Dir name is '$dir_name'"

repo_dir=$(dirname $dir_name)
echo "Repo dir is '$repo_dir'"

base_name=$(basename $real_path)
echo "Base name is '$base_name'"
