#!/usr/bin/env bash

is_prime() {
    n=$1

    # 0 and 1 are not prime
    [ "$n" -lt 2 ] && return 1

    i=2
    while [ $((i * i)) -le "$n" ]; do
        if [ $((n % i)) -eq 0 ]; then
            return 1
        fi
        i=$((i + 1))
    done

    return 0
}

n=2

while true; do
    if is_prime "$n"; then
        echo "$n"
    fi
    n=$((n + 1))
done
